repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-docstring-first
  - id: fix-encoding-pragma
  - id: detect-private-key
  - id: name-tests-test
    args: [--pytest-test-first]
  - id: no-commit-to-branch
    args: [--branch, main]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: "v0.0.280"
  hooks:
  - id: ruff
    name: Static code analysis and error auto-correction (Ruff)
    args: [--config, pyproject.toml, --fix, --exit-non-zero-on-fix]
    files: |
      (?x)^(
        sootworks/.*|
        test/.*
      )$
    types_or: [python, pyi, jupyter]
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black
    name: Code auto-formatting (Black)
    args: [--config, pyproject.toml]
    files: |
      (?x)^(
        sootworks/.*|
        test/.*
      )$
    types_or: [python, pyi, jupyter]
